// 剪贴板采集：系统没有剪贴板变化通知，只能轮询 changeCount（0.3s），变了才读内容。
// 读取顺序：隐私标记 → 排除的来源 App → 文件 → 文本（附带格式）→ 图片。
// 启动时直接对齐当前 changeCount，不把启动前就在剪贴板里的内容记一遍。

import AppKit

final class ClipboardWatcher {
  /// nspasteboard.org 约定：密码管理器等打了这些标记的内容不进历史
  static let privateMarkers: Set<NSPasteboard.PasteboardType> = [
    .init("org.nspasteboard.ConcealedType"),
    .init("org.nspasteboard.TransientType"),
    .init("org.nspasteboard.AutoGeneratedType"),
  ]
  /// 超过的文本不记录（防内存暴涨）
  static let maxTextBytes = 5 * 1_048_576
  /// 带格式数据超过就只存纯文本
  static let maxRichBytes = 2 * 1_048_576

  /// 新文本入库后回调（复制即译，M4）
  var onText: ((String) -> Void)?
  private let store: ClipboardStore
  private var timer: Timer?
  private var lastChangeCount = NSPasteboard.general.changeCount
  private var isPaused = false

  init(store: ClipboardStore) {
    self.store = store
  }

  func start() {
    timer = Timer.scheduledTimer(withTimeInterval: 0.3, repeats: true) { [weak self] _ in
      MainActor.assumeIsolated { self?.poll() }
    }
    timer?.tolerance = 0.1
  }

  /// 划词取词期间暂停：那次 ⌘C 和还原都不是用户的复制
  func pause() { isPaused = true }

  func resume() {
    lastChangeCount = NSPasteboard.general.changeCount
    isPaused = false
  }

  private func poll() {
    let pasteboard = NSPasteboard.general
    let changeCount = pasteboard.changeCount
    guard !isPaused, changeCount != lastChangeCount else { return }
    lastChangeCount = changeCount
    guard changeCount != Paster.ownChangeCount, let types = pasteboard.types,
      Self.privateMarkers.isDisjoint(with: types)
    else { return }

    let defaults = UserDefaults.standard
    let source = NSWorkspace.shared.frontmostApplication.flatMap { $0 == .current ? nil : $0 }
    if ClipboardFilter.isExcluded(
      appName: source?.localizedName, bundleID: source?.bundleIdentifier,
      excluded: defaults.stringArray(forKey: Prefs.clipboardExcludedApps) ?? [])
    {
      return
    }
    var item = ClipItem(
      kind: .text, sourceName: source?.localizedName, sourceBundleID: source?.bundleIdentifier)

    let fileOptions: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
    if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: fileOptions) as? [URL],
      !urls.isEmpty
    {
      item.kind = .file
      item.filePaths = urls.map(\.path)
      store.record(item)
      return
    }

    if let text = pasteboard.string(forType: .string) {
      guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
        text.utf8.count <= Self.maxTextBytes,
        !(defaults.bool(forKey: Prefs.clipboardBlockSensitive)
          && ClipboardFilter.looksSensitive(text))
      else { return }
      item.text = text
      var rich: Data?
      if defaults.bool(forKey: Prefs.clipboardKeepRichText) {
        for (type, richType) in [
          (NSPasteboard.PasteboardType.rtf, ClipItem.RichType.rtf), (.html, .html),
        ] {
          if let data = pasteboard.data(forType: type), data.count <= Self.maxRichBytes {
            (item.richType, rich) = (richType, data)
            break
          }
        }
      }
      store.record(item, rich: rich)
      onText?(text)
      return
    }

    for (type, isPNG) in [(NSPasteboard.PasteboardType.png, true), (.tiff, false)] {
      guard let data = pasteboard.data(forType: type) else { continue }
      item.kind = .image
      let images = store.images
      Task { [item] in
        guard let info = await images.save(data, isPNG: isPNG, id: item.id) else { return }
        var saved = item
        saved.image = info
        store.record(saved)
      }
      return
    }
  }
}
