// 剪贴板采集：系统没有剪贴板变化通知，只能轮询 changeCount（0.3s），变了才读内容。
// 读取顺序：隐私标记 → 来源（通用剪贴板 / 写入方的来源标记 / 本 App 自己的窗口 / 前台 App）→ 排除的来源 App → 文件 →
// 文本（总是附带格式）→ 图片。在自家浮层里 ⌘C（翻译原文 / 译文、剪贴板备注等，走 NSText.copy 不经 Paster，
// 复制那一刻记下 Paster.panelCopyChangeCount）来源记成本 App（没有来源）、不触发复制即译（体检 B20）。
// 启动时直接对齐当前 changeCount，不把启动前就在剪贴板里的内容记一遍。
// 两种暂停互不相干：pause() / resume() 给划词取词用；isUserPaused 是菜单栏「暂停记录剪贴板」（不存盘，重启自动恢复）。

import AppKit

final class ClipboardWatcher {
  /// 不进历史的标记：nspasteboard.org 约定的三种（密码管理器等），加上常见工具自己的（体检 B4）：
  /// 旧版 Keyboard Maestro 等的生成标记、1Password 7、TypeIt4Me、Keyboard Maestro、KeeWeb
  static let privateMarkers: Set<NSPasteboard.PasteboardType> = [
    .init("org.nspasteboard.ConcealedType"),
    .init("org.nspasteboard.TransientType"),
    .init("org.nspasteboard.AutoGeneratedType"),
    .init("Pasteboard generator type"),
    .init("com.agilebits.onepassword"),
    .init("com.typeit4me.clipping"),
    .init("de.petermaurer.TransientPasteboardType"),
    .init("net.antelle.keeweb"),
  ]
  /// nspasteboard.org 约定：写入方把自己的 bundle ID 放在这个类型里
  static let sourceMarker = NSPasteboard.PasteboardType("org.nspasteboard.source")
  /// 通用剪贴板（从 iPhone / 另一台 Mac 过来的）
  static let remoteMarker = NSPasteboard.PasteboardType("com.apple.is-remote-clipboard")
  /// 超过的文本不记录（防内存暴涨）
  static let maxTextBytes = 5 * 1_048_576
  /// 带格式数据超过就只存纯文本
  static let maxRichBytes = 2 * 1_048_576

  /// 新文本入库后回调（复制即译，M4）
  var onText: ((String) -> Void)?
  /// 用户在菜单栏暂停了记录：changeCount 照走，但不记、也不触发复制即译
  var isUserPaused = false
  private let store: ClipboardStore
  private var timer: Timer?
  private var lastChangeCount = NSPasteboard.general.changeCount
  private var isPaused = false

  init(store: ClipboardStore) {
    self.store = store
  }

  func start() {
    timer = Timer.scheduledTimer(withTimeInterval: 0.3, repeats: true) { [weak self] _ in
      MainActor.assumeIsolated { self?.poll() }
    }
    timer?.tolerance = 0.1
  }

  /// 划词取词期间暂停：那次 ⌘C 和还原都不是用户的复制
  func pause() { isPaused = true }

  func resume() {
    lastChangeCount = NSPasteboard.general.changeCount
    isPaused = false
  }

  /// 这次复制的来源（体检 B6）：通用剪贴板过来的是「其他设备」（没有 bundle ID，来源筛选里不列）；
  /// 写入方打了来源标记就用它（名字按 bundle ID 查，排除的 App 照样认得出）；在本 App 自己的窗口里复制的
  /// （ownWindow：在自家浮层里 ⌘C，或本 App 在前台）没有来源（体检 B20）；都没有才用轮询时的前台 App（推测值）
  static func source(
    ownWindow: Bool = false, remote: Bool, marker: String?,
    frontmost: (name: String?, bundleID: String?)?, appName: (String) -> String?
  ) -> (name: String?, bundleID: String?) {
    if remote { return ("其他设备", nil) }
    if let marker, !marker.isEmpty { return (appName(marker) ?? marker, marker) }
    if ownWindow { return (nil, nil) }
    return frontmost ?? (nil, nil)
  }

  private func poll() {
    let pasteboard = NSPasteboard.general
    let changeCount = pasteboard.changeCount
    guard !isPaused, changeCount != lastChangeCount else { return }
    lastChangeCount = changeCount
    guard !isUserPaused, changeCount != Paster.ownChangeCount, let types = pasteboard.types,
      Self.privateMarkers.isDisjoint(with: types)
    else { return }

    let defaults = UserDefaults.standard
    // 浮层不激活本 App：在它里面复制时前台还是别的 App，靠复制那一刻记下的 changeCount 认
    let ownWindow =
      changeCount == Paster.panelCopyChangeCount
      || NSWorkspace.shared.frontmostApplication == .current
    let front = NSWorkspace.shared.frontmostApplication.flatMap { $0 == .current ? nil : $0 }
    let source = Self.source(
      ownWindow: ownWindow, remote: types.contains(Self.remoteMarker),
      marker: pasteboard.string(forType: Self.sourceMarker),
      frontmost: front.map { ($0.localizedName, $0.bundleIdentifier) },
      appName: AppIcons.name(for:))
    if ClipboardFilter.isExcluded(
      bundleID: source.bundleID,
      excluded: Set(defaults.stringArray(forKey: Prefs.clipboardExcludedBundleIDs) ?? []))
    {
      return
    }
    var item = ClipItem(kind: .text, sourceName: source.name, sourceBundleID: source.bundleID)

    let fileOptions: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
    if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: fileOptions) as? [URL],
      !urls.isEmpty
    {
      item.kind = .file
      item.filePaths = urls.map(\.path)
      store.record(item)
      return
    }

    if let text = pasteboard.string(forType: .string) {
      guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
        text.utf8.count <= Self.maxTextBytes,
        !(defaults.bool(forKey: Prefs.clipboardBlockSensitive)
          && ClipboardFilter.looksSensitive(text))
      else { return }
      item.text = text
      // 格式总是记下来（体检 A5）：粘贴时用不用由「默认粘贴为纯文本」和 ⌥↩ 决定
      var rich: Data?
      for (type, richType) in [
        (NSPasteboard.PasteboardType.rtf, ClipItem.RichType.rtf), (.html, .html),
      ] {
        if let data = pasteboard.data(forType: type), data.count <= Self.maxRichBytes {
          (item.richType, rich) = (richType, data)
          break
        }
      }
      store.record(item, rich: rich)
      // 自家窗口里复制的不触发复制即译（来源标记 / 通用剪贴板过来的照常）
      if !(ownWindow && source.name == nil && source.bundleID == nil) { onText?(text) }
      return
    }

    for (type, isPNG) in [(NSPasteboard.PasteboardType.png, true), (.tiff, false)] {
      guard let data = pasteboard.data(forType: type) else { continue }
      item.kind = .image
      let images = store.images
      Task { [item] in
        guard let info = await images.save(data, isPNG: isPNG, id: item.id) else { return }
        var saved = item
        saved.image = info
        store.record(saved)
      }
      return
    }
  }
}
